name: Steadfast Payment Request Automation

on:
  schedule:
    # প্রতিদিন সকাল 10:30 AM Bangladesh Time (04:30 UTC)
    - cron: '30 4 * * *'
  workflow_dispatch: # Manual trigger এর জন্য

jobs:
  run-automation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.15.2
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Install ChromeDriver
      run: |
        # Get Chrome version
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
        echo "Chrome version: $CHROME_VERSION"
        
        # Install ChromeDriver using apt
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        
        # Create symlink
        sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
        
        # Verify installation
        echo "Verifying installation..."
        google-chrome --version
        chromedriver --version
        which chromedriver
    
    - name: Run automation script
      run: |
        echo "Starting automation..."
        python steadfast_automation.py
      env:
        PYTHONUNBUFFERED: 1
    
    - name: Upload error artifacts (if failed)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: |
          error_screenshot.png
          error_page_source.html
          *.png
          *.html
        if-no-files-found: ignore
    
    - name: Upload success artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: success-logs
        path: |
          success_screenshot.png
          *.png
        if-no-files-found: ignore
