name: Steadfast Payment Request Automation

on:
  schedule:
    # প্রতিদিন সকাল 10:30 AM Bangladesh Time (04:30 UTC)
    - cron: '30 4 * * *'
  workflow_dispatch: # Manual trigger এর জন্য

jobs:
  run-automation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install selenium==4.15.2
        pip install webdriver-manager
    
    - name: Install Chrome and ChromeDriver
      run: |
        # Chrome install
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # ChromeDriver install
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
        wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
        
        # Verify installation
        google-chrome --version
        chromedriver --version
    
    - name: Run automation script
      run: python steadfast_automation.py
      env:
        DISPLAY: :99
