name: Steadfast Payment Request Automation

on:
  schedule:
    # প্রতিদিন সকাল 10:30 AM Bangladesh Time (04:30 UTC)
    - cron: '30 4 * * *'
  workflow_dispatch: # Manual trigger এর জন্য

jobs:
  run-automation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install selenium
        pip install webdriver-manager
    
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
    
    - name: Run automation script
      run: python steadfast_automation.py
      env:
        DISPLAY: :99
